# Generated by Django 3.1.2 on 2020-10-16 02:09

from django.db import migrations, models
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=teams.models.uploaded_location, width_field='width_field'),
        ),
    ]
