# Generated by Django 3.1.2 on 2020-10-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
