# Generated by Django 3.1.2 on 2020-10-16 03:51

from django.db import migrations
import django_resized.forms
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20201016_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[200, 200], upload_to=teams.models.uploaded_location),
        ),
    ]
