# Generated by Django 3.1.2 on 2020-10-16 05:57

from django.db import migrations
import django_resized.forms
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20201016_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, height_field='height_field', keep_meta=True, null=True, quality=90, size=[220, 220], upload_to=teams.models.uploaded_location, width_field='width_field'),
        ),
    ]
