# Generated by Django 3.1.2 on 2020-10-16 05:57

from django.db import migrations, models
import django_resized.forms
import photography.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('tagline', models.CharField(max_length=250)),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, size=[520, 520], upload_to=photography.models.uploaded_location)),
                ('description', models.TextField(blank=True, null=True)),
                ('facebook', models.CharField(max_length=250)),
                ('instagram', models.CharField(max_length=250)),
                ('twitter', models.CharField(max_length=250)),
                ('linkedin', models.CharField(max_length=250)),
                ('googleplus', models.CharField(max_length=250)),
            ],
        ),
    ]
